import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar/page";
import Banner from "./Banner/page";
import FeaturedRecipes from "./Featured.jsx/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="max-w-[1600px] w-full mx-auto px-4 md:px-8 lg:px-12">
          <Navbar></Navbar>
          <main>
            <Banner></Banner>
            <FeaturedRecipes></FeaturedRecipes>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}